### ISSUE TITLE
Install for all domains

### ISSUE THREAD

**Issue by scith** [alexAubin/letsencrypt_ynh#1]
Hi,
If it can help, here is a script we developped for the Rainloop package that loops through all domains added to YunoHost:

alldomains=`ldapsearch -LLL -x -b ou=domains,dc=yunohost,dc=org -s one "objectclass=top" virtualdomain | grep -v "dn:" | sed "s/virtualdomain://"`
    for domain in $alldomains ; do
        # Your action
    done

Perhaps during the install of letsencrypt we could have an option asking if letsencrypt should be installed for all domains, and if yes use this script to loop through each

Thanks

**Comment by alexAubin** [comment]
Oh that sounds cool, thanks ! I'll have a look.

**Comment by mbugeia** [comment]
@scith there is already a helper in yunohost to list all domains, no need for a ""complicated" ldap search ;)
yunohost domain list --output-as plain

**Comment by scith** [comment]
Thanks @mbugeia I need to try that :)
Where di you find this helper?
Cheers

**Comment by mbugeia** [comment]
I read the manual and the source code.
You can use -h with every yunohost command for detailled help like yunohost domain -h
Also the --output-as {json,plain] is available for all command I think you can also use --plain or --json but it's deprecated.

**Comment by alexAubin** [comment]
I tried the command but the option --output-as doesn't seem to work on my install (debian wheezy, raspberry pi, installed a few monthes ago).

--json works, but not --plain.

Anyway the command without options (i.e. yunohost domain list) works, I guess I just need to parse it ?

**Comment by mbugeia** [comment]
Hum that's probably because I'm running yunohost testing not stable. You can try yunohost -h to see if there is an option to display in plaintext. If not I guess you'll have to parse it.

**Comment by alexAubin** [comment]
I made this first attempt of install on all domains, in a new branch for now. I tried to put several tests and checks to have a reasonable behavior in case something goes wrong : 
- if every initial cert fetch fails, install is aborted ;
- otherwise, if one but not all fails, install script just show a warning at the end.

I tested it in a VM but it's not fully tested, but hopefully it should be okay, so if you want to give it a try you're welcome.

Uninstall/remove script should also do a reasonable job.

**Comment by scith** [comment]
The branch works very nice on all my domains thanks!
![domains_pic](https://framapic.org/Lrp9b3vqUypn/4fXRpqNbqVQK)

Another suggestion:
- Make hooks: post_domain_add and post_domain_remove to create the certificates after a domain is added or removed

But I'm not sure that's needed if let's encrypt becomes part of YunoHost core... We'll see

**Comment by alexAubin** [comment]
Yes, this is a tricky question, which is also discussed [here](https://github.com/YunoHost/yunohost/pull/114). Since you need the DNS stuff working to fetch the certificate, I'd rather have a button or command line that allows to fetch the certificate once the DNS is working.

**Comment by luc38090** [comment]
How to use the multidomain branch in yunohost ? Wich URL to use ?

**Comment by alexAubin** [comment]
Hi,

I just merged the multidomain branch in master, so you can now just use the standard git url

(Otherwise the only way I know is to clone the repo, checkout the branch then call `yunohost app install /path/to/package`)

**Comment by luc38090** [comment]
Working perfectly !
Thanks !
