### ISSUE TITLE
How to Multi-Domain or even just domain.tld or www.domain.tld

### ISSUE THREAD

**Issue by benborges** [alexAubin/letsencrypt_ynh#13]
How do you plan to assign new certs if the app can only be installed once ?

I mean how do I relaunch the process in my use case : 

I started with a domain without www.
then I noticed plenty of users complaining the www.domain.tld were redirecting them to /yunohost/admin
so I added www.domain.tld to the list of domain..

Now How do I assign a certificate to www.domain.tld if your lets encrypt yunohost app is already installed and serving the same domain but without the www. part.

i'm not sure my situation is clear enough...

**Comment by alexAubin** [comment]
Your use case is clear,

however, I think this app was aimed to be sort of a workaround while support for Let's Encrypt is implemented directly into the mechanics of Yunohost as part of the domain management.

While it's possible to do more elaborate things with this app (for instance develop a web interface allowing to add domains without having to reinstall the app), it would really be cleaner to have this properly implemented inside Yunohost and not just an "external" app, so we need to check what exactly we're doing about this and the timescale.

Cheers !

**Comment by alexAubin** [comment]
Closing because app is now deprecated thanks to built-in integration in Yunohost 2.5
