### ISSUE TITLE
Installing broke nginx configuration with references to missing certificate files

### ISSUE THREAD

**Issue by Bugsbane** [alexAubin/letsencrypt_ynh#14]
Hey there,

I'd already installed let's encrypt certs on my Yunohost 2.4 install, following the how-to post on the forums. When the certs expired though, I thought I'd give the app a try, so I chose install, and it hit an error. Afterwards nginx breaks and won't restart, stating:
Jul 09 15:00:22 yunohost nginx[28033]: nginx: [emerg] BIO_new_file("/etc/yunohost/certs/mydomain.com/crt.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/yunohost/certs/mydomain.com/crt.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

When I look at those paths, as stated, the files don't actually exist.

Is there any further info I can give to help debug? I'm running a VM with recent snapshots, so it's easy to experiment and revent in just a few clicks.

**Comment by TopheC** [comment]
Same story for me with same result.
Seems LE certificates working only the first time, with possibility to renew or reinstall correctly.
Any idea ?

**Comment by Bugsbane** [comment]
I ended up manually recreating the certs with the LE command line app, and then looking up the paths it was looking for them in and putting them there. I imagine it'll break again next time something updates, but it's working again for me now, temporarily.

**Comment by TopheC** [comment]
Hi Bugsbane, can you explain a little or give reference of the command/method you used, please ?
alexAubin will work on a new version of his code, but in the meantime, i need some help to have my server up again, asap... Thx in advance.

**Comment by alexAubin** [comment]
@TopheC : did you retry the step-by-step manual installation ? (i.e. the tutorial on Yunohost forum ?) If so, which step didn't work ? Did you get to try the letsencrypt-auto --renew thing ?

**Comment by Bugsbane** [comment]
Sorry @TopheC , it took me a long time and I tried a bunch of different things, many of which I'm sure either didn't work, or made things worse before getting the pieces right. It was a while back, and I doon't remember exactly how, or which pieces did the trick, other than to say, I remember there was an nginx config file (under domainname.conf?) that pointed to where it was looking for the certs and that I ran the let's encrypt app again, and put the cert files where it seemed to be looking for them.

That's about all I remember. Sorry. :(

**Comment by TopheC** [comment]
@alexAubin : i have tried several times the manual installation... i'll give a try the --renew option.
@Bugsbane : it's OK, i'll give a try to move the nginx config files.
Stay tuned :)

**Comment by Bugsbane** [comment]
@TopheC I didn't move any .conf files. I just looked at the .conf files to figure out where Nginx was looking for the Let's Encrypt certificate files.

**Comment by TopheC** [comment]
Hello, i have done some changes to domain names on my Yunohost 2.4 and finally completely broke my setup... but i've learned a lot try to repair it :)  
Now, i have done my setup again, from scratch, payed attention to docs, and it is completely up and running, with Letsencrypt certs installed, and a A+ result from SSL test !
Thanks again for your help & advices +1:
