### ISSUE TITLE
Cannot reinstall app in web gui or command-line

### ISSUE THREAD

**Issue by stevenroh** [alexAubin/letsencrypt_ynh#17]
Hello,

I had few problems with renewal of certificate. So I removed the app to reinstall it. Now I've trouble installing it again with web gui or command-line. Any idea ? System is up to date.

![capture du 2016-08-15 21-12-24](https://cloud.githubusercontent.com/assets/1651603/17676154/7b21da6a-632d-11e6-8605-8f16ae255f4e.png)

Thanks

**Comment by koko-ng** [comment]
Maybe just try to 'touch /etc/cron.weekly/certificateRenewer' it seems that the installer tries to delete this file that is already deleted.

**Comment by alexAubin** [comment]
Closing because app is now deprecated thanks to built-in integration in Yunohost 2.5
