### ISSUE TITLE
Issues with uninstall, multi-instances, and applying certs

### ISSUE THREAD

**Issue by Codethematrix** [alexAubin/letsencrypt_ynh#18]
First off I am truly a fan! I really am wanting to learn how to get my hands dirty with code so I can do more than just install and "complain". Kudos once again, I'll be joining the coding world sometime this year.

---

My issue has multiple parts to it. I will break them up and explain what happens.
a.) uninstall - when the script is uninstalled it causes the server to "lag" at first then upon page reload it goes into a cert error. I can't access the yunohost site or the domains hosted on it from any desktop devices. I have to go onto a mobile device to access the yunohost admin panel to reinstall the script to get things working again.

b.) multi-instances (multiple domains). Once I install the application it gives the usual options for which doamin to use as the main. It instantly secure that domain, but not the others. I have tried a few different methods including the one I am about to attempt after this post.
method 1. install on main domain and then reinstall on every domain (shows failure, but works sometimes) 2. Install letsencrypt first before adding any other domains.

c.) (Goes with B) certs do not get issued to domains added after the main or other ones that are previously hosted before the letsencrypt installation.

**Comment by alexAubin** [comment]
Closing because app is now deprecated thanks to built-in integration in Yunohost 2.5
