### ISSUE TITLE
Do not install stuff in /root

### ISSUE THREAD

**Issue by julienmalik** [alexAubin/letsencrypt_ynh#4]
Please prefer something like /opt/yunohost/letsencrypt (in line with what a number of other apps are doing) to put all stuff installed by your app.

**Comment by alexAubin** [comment]
Yes, that's a good point. Didn't know where was the right place to put that when I first implemented the package. I'll change that in the various scripts and test it.

**Comment by alexAubin** [comment]
Hey,

I made a bunch of commits, that should fix the issue. Also added stuff to the upgrade script that should allow a smooth transition.

Cheers,

Alex
