### ISSUE TITLE
Un mail pour ne rien dire

### ISSUE THREAD

**Issue by maniackcrudelis** [alexAubin/letsencrypt_ynh#7]
Salut,

je viens d'installer Let's Encrypt sur mon serveur de prod, c'est passé tout seul, ça fait plaisir!
Par contre, je viens de recevoir un mail inutile pour me dire qu'il n'y a rien à faire.

> ```
> /etc/cron.weekly/certificateRenewer:
> Checking domain.tld certificate ...
> > No need to renew it.
> ```

Et je pense que, partit comme ça, je vais avoir droit à ce mail toutes les semaines pour me dire qu'il n'y a rien à faire.
Ce serait bien de n'être averti que si il y a vraiment quelque chose à dire ;)

**Comment by alexAubin** [comment]
Yope,

oui, ta remarque est judicieuse :). Historiquement j'ai choisi d'en envoyer un quand meme le temps de vraiment tester le renew automatique et pour être informé que le script s'executait correctement.

Je vais regarder comment modifier le script pour ne rien printer si tout va bien

**Comment by alexAubin** [comment]
Commit  [89faed3](https://github.com/alexAubin/letsencrypt_ynh/commit/89faed3bc05e8ef9f8274c7596bfe3d3ed1554d5) should fix this (just commented two lines). Also the upgrade script does the job of updating the cron script.

Cheers !
