### ISSUE TITLE
let's encrypt CA is missing

### ISSUE THREAD

**Issue by zamentur** [alexAubin/letsencrypt_ynh#8]
Hi,

It seems that this let's encrypt app don't put the ca of let's encrypt inside /etc/yunohost/certs/DOMAIN .

With the new version of testing it triggers an error on dovecot 
https://forum.yunohost.org/t/probleme-mail-dovecot-ne-demarre-plus/1482

Thanks

**Comment by julienmalik** [comment]
Fixed in unstable : https://github.com/YunoHost/yunohost/commit/3339cd029abdf43ba1577ef977518961331daa9d

you can close

**Comment by alexAubin** [comment]
_/me sits at desk, happy and enthusiast about fixing the issue_

_/me sees issue is already fixed_

[okay.jpg](http://i.imgur.com/xYMGOGc.jpg)
