### ISSUE TITLE
Package doesn't work on Yunohost 2.4 ?

### ISSUE THREAD

**Issue by alexAubin** [alexAubin/letsencrypt_ynh#9]
From [this post](https://forum.yunohost.org/t/how-to-install-let-s-encrypt-certificates/1075/77)

> Je viens d'essayer l'install sur yunohost 2.4 et ça crash.
> 
> Ça termine simplement par un serveur (je suppose que le message fait reference a nginx) qui refuse de redémarrer mais rien ne casse et l'app n’apparaît pas dans la liste. Donc rien de très grave mais assez ennuyeux.
> 
> Je peux regarder plus en détails si c'est nécessaire. Mais je suppose que c'est simplement que les apps 2.2 et 2.4 ne sont pas compatibles. En attendant, j’installerais a la main.

To be checked.

**Comment by bachy** [comment]
pareille sur une install ynh 2.4 toute fraiche :

```
$ yunohost app install https://github.com/alexAubin/letsencrypt_ynh
Choose a main domain: synesthesie.io
Choose an admin user: bach
Install for all domains ? [Yes | No] (default: Yes): 
Warning: mkdir: cannot create directory ‘/root/.letsencrypt-backupDuringUninstall’: File exists
Warning: rm: cannot remove ‘/etc/cron.weekly/certificateRenewer’: No such file or directory
Warning: mv: cannot stat ‘/etc/letsencrypt’: No such file or directory
Error: Installation failed
```

**Comment by bachy** [comment]
bon ben je viens de re-essayer et ça a marché :)

**Comment by M5oul** [comment]
Fonctionne également sur mon serveur.

**Comment by alexAubin** [comment]
Okay, I'm closing the issue then. Thanks for the feedback ! :)

**Comment by Jibec** [comment]
same in here, I was waiting this ticket to be close to retry !
But there still is an issue somewhere (i replaced domain names)

Erreur serveur inattendue (0 error)
- sudo service nginx restart
- sudo cp ../conf/nginx.conf /etc/nginx/conf.d/mondomaine.fr.d/000-letsencrypt.conf
- for domain in '$domainsList'
- AT_LEAST_ONE_FAILED=False
- AT_LEAST_ONE_SUCCESS=False
- sudo yunohost app setting letsencrypt installDomains -v ' mondomaine.fr jb.mondomaine.fr ici.mondomaine.fr '
- domainsList=' mondomaine.fr jb.mondomaine.fr ici.mondomaine.fr '

++ sed 's/ //g'

++ sed 's/ - //g'

++ sed s/domains://g

++ grep .

++ tr '\n' ' '

++ sudo yunohost domain list
- [[ Yes == \Y\e\s ]]
- domainsList=mondomaine.fr
- sudo mkdir -p /tmp/letsencrypt-auto
- sudo cp ../conf/letsencrypt.conf /etc/letsencrypt/conf.ini
- sed -i 's|WEBROOT_PATH|/tmp/letsencrypt-auto|g' ../conf/letsencrypt.conf
- sed -i 's|ADMIN_EMAIL|jibec@mondomaine.fr|g' ../conf/letsencrypt.conf
- '[' '!' -d /etc/letsencrypt ']'

No installers seem to be present and working on your system; fix that or try running certbot with the "certonly" command

Installation succeeded.

Installing Python packages...

Creating virtual environment...
- sudo /opt/yunohost/letsencrypt//letsencrypt-auto

Clonage dans '/opt/yunohost/letsencrypt'...
- sudo git clone https://github.com/letsencrypt/letsencrypt /opt/yunohost/letsencrypt/
- sudo yunohost app setting letsencrypt installdir -v /opt/yunohost/letsencrypt/
- webrootdir=/tmp/letsencrypt-auto
- installdir=/opt/yunohost/letsencrypt/
- sudo yunohost app setting letsencrypt mainDomain -v mondomaine.fr
- sudo yunohost app setting letsencrypt admin -v jibec
- [[ ! 0 -eq 0 ]]
- grep -q '"username": "jibec"'
- sudo yunohost user list --json
- installForAllDomains=Yes
- admin=jibec
- mainDomain=mondomaine.fr
- app=letsencrypt

Exécution du script « /var/cache/yunohost/from_file/ffsync_ynh-master/letsencrypt_ynh-master/scripts/install »...

Terminé.

Extraction...

Téléchargement...

**Comment by lapineige** [comment]
Un autre test : sur un RPi 3 sous Debian Jessie / yunohost 2.4, ça fonctionne parfaitement, pour plusieurs domaines.
